Repository kubernetes-csi/external-health-monitor, pull requests merged in 2020-07, with the labels that each got.

#14 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#15 fix: add the clusterrole of event for controller
  deploy/kubernetes/external-health-monitor-controller/rbac.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#16 master: update release-tools
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#17 Enable cloud build
  .cloudbuild.sh
  cloudbuild.yaml
  cmd/csi-external-health-monitor-agent/Dockerfile
  cmd/csi-external-health-monitor-controller/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#19 fix: assign node name to agent
  cmd/csi-external-health-monitor-agent/main.go
  deploy/kubernetes/external-health-monitor-agent/daemonset.yaml
  deploy/kubernetes/external-health-monitor-controller/deployment.yaml
  pkg/agent/pv_monitor_agent.go
  pkg/util/env.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M
