Repository kubernetes-csi/external-health-monitor, pull requests merged in 2020-12, with the labels that each got.

#49 Introducing the http-endpoint flag
  README.md
  cmd/csi-external-health-monitor-agent/main.go
  cmd/csi-external-health-monitor-controller/main.go
  deploy/kubernetes/external-health-monitor-agent/daemonset.yaml
  deploy/kubernetes/external-health-monitor-controller/deployment.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#48 Fix for NotFound error when NodeGetVolumeStats
  pkg/agent/pv_monitor_agent.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#51 Add changelog for 0.2
  CHANGELOG/CHANGELOG-0.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L
