Repository kubernetes-csi/external-health-monitor, pull requests merged in 2020-08, with the labels that each got.

#23 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#22 feature: agent sends event to the pod
  pkg/csi-handler/pv_checker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#24 master: update release-tools
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#27 fix: change image tag of controller and agent
  deploy/kubernetes/external-health-monitor-agent/daemonset.yaml
  deploy/kubernetes/external-health-monitor-controller/deployment.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#25 Add readme for alpha release
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/M

#32 change the image tag to v0.1.0
  deploy/kubernetes/external-health-monitor-agent/daemonset.yaml
  deploy/kubernetes/external-health-monitor-controller/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#33 doc: update description of flags to README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/M

#28 Add changelog
  CHANGELOG/CHANGELOG-0.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
