Repository kubernetes-csi/external-health-monitor, pull requests merged in 2021-04, with the labels that each got.

#63 Remove references to "local" PVs
  cmd/csi-external-health-monitor-controller/main.go
  pkg/controller/node_watcher.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#64 remove the build option of agent
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#65 Add changelog for 0.3.0 and update README
  CHANGELOG/CHANGELOG-0.3.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#68 clean: remove deployment file of agent
  deploy/kubernetes/external-health-monitor-agent/daemonset.yaml
  deploy/kubernetes/external-health-monitor-agent/rbac.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L
