Repository kubernetes-csi/external-health-monitor, pull requests merged in 2021-08, with the labels that each got.

#84 Update k8s dependencies to v1.22.0
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, sig/storage, size/M

#85 Use csi-lib-utils v0.10.0
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note

#86 Clean up .travis.yml
  .travis.yml
Labels: kind/cleanup, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#90 Add command line arguments to configure leader election options
  README.md
  cmd/csi-external-health-monitor-controller/main.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#88 Add changelog for 0.4
  CHANGELOG/CHANGELOG-0.4.md
  deploy/kubernetes/external-health-monitor-controller/deployment.yaml
Labels: release-note-none, approved, cncf-cla: yes, lgtm, kind/documentation, size/L
