Repository kubernetes-csi/external-health-monitor, pull requests merged in 2024-05, with the labels that each got.

#251 Add changelog for 1.12
  CHANGELOG/CHANGELOG-0.12.md
Labels: release-note-none, approved, cncf-cla: yes, lgtm, kind/documentation, size/M

#246 Support contextual logging
  Makefile
  cmd/csi-external-health-monitor-controller/main.go
  pkg/controller/framework_test.go
  pkg/controller/node_watcher.go
  pkg/controller/pv_monitor_controller.go
  pkg/csi-handler/pv_checker.go
  pkg/csi-handler/pv_checker_test.go
  pkg/csi-handler/pv_handler_test.go
  pkg/mock/mock.go
  pkg/util/util_test.go
  release-tools/.github/dependabot.yaml
  release-tools/.github/workflows/codespell.yml
  release-tools/.github/workflows/trivy.yaml
  vendor/k8s.io/klog/v2/ktesting/init/init.go
  vendor/k8s.io/klog/v2/ktesting/options.go
  vendor/k8s.io/klog/v2/ktesting/setup.go
  vendor/k8s.io/klog/v2/ktesting/testinglogger.go
  vendor/modules.txt
Labels: kind/feature, kind/cleanup, approved, cncf-cla: yes, lgtm, size/XXL, priority/important-longterm, release-note, wg/structured-logging

#253 Update changelog for v0.12
  CHANGELOG/CHANGELOG-0.12.md
Labels: kind/cleanup, release-note-none, approved, cncf-cla: yes, lgtm, size/S
